name: 🐛 Bug Fix
description: Submit a fix for a bug or issue
title: "[BUG] "
labels: ["bug", "fix"]
assignees: []

body:
  - type: markdown
    attributes:
      value: |
        Thanks for fixing a bug! Please provide detailed information about the issue and your solution.

  - type: input
    id: bug-summary
    attributes:
      label: Bug Summary
      description: Brief description of the bug being fixed
      placeholder: "Login form validation fails on special characters"
    validations:
      required: true

  - type: input
    id: related-issues
    attributes:
      label: Related Issues
      description: Link the bug reports this PR fixes
      placeholder: "Fixes #123, Closes #456"
    validations:
      required: true

  - type: textarea
    id: expected-behavior
    attributes:
      label: Expected Behavior
      description: What should have happened?
      placeholder: "Describe the expected behavior..."
    validations:
      required: true

  - type: textarea
    id: actual-behavior
    attributes:
      label: Actual Behavior
      description: What actually happened?
      placeholder: "Describe what went wrong..."
    validations:
      required: true

  - type: textarea
    id: reproduction-steps
    attributes:
      label: Steps to Reproduce
      description: How to reproduce the bug
      placeholder: |
        1. Go to...
        2. Click on...
        3. See error...
    validations:
      required: true

  - type: dropdown
    id: bug-severity
    attributes:
      label: Bug Severity
      description: How severe was this bug?
      options:
        - Low - Minor issue, workaround available
        - Medium - Significant issue affecting some users
        - High - Major issue affecting many users
        - Critical - System breaking or security issue
    validations:
      required: true

  - type: textarea
    id: root-cause
    attributes:
      label: Root Cause Analysis
      description: What was causing the bug?
      placeholder: "Explain the underlying cause of the issue..."
    validations:
      required: true

  - type: textarea
    id: solution-description
    attributes:
      label: Solution Description
      description: Describe the changes you made to fix the bug
      placeholder: "Explain how your changes address the root cause..."
    validations:
      required: true

  - type: checkboxes
    id: environment-tested
    attributes:
      label: Environment Tested
      description: Which environments have you tested the fix in?
      options:
        - label: Local development
          required: true
        - label: Staging/Test environment
        - label: Multiple browsers (Chrome, Firefox, Safari, Edge)
        - label: Mobile devices
        - label: Different operating systems

  - type: checkboxes
    id: testing-completed
    attributes:
      label: Testing Verification
      description: Verification steps completed
      options:
        - label: Bug reproduced on original code
          required: true
        - label: Fix verified to resolve the issue
          required: true
        - label: No regression in related functionality
          required: true
        - label: Edge cases tested
        - label: Added regression test
          required: true

  - type: textarea
    id: testing-steps
    attributes:
      label: Manual Testing Steps
      description: Steps to verify the fix works
      placeholder: |
        1. Apply the fix...
        2. Test the scenario...
        3. Verify the issue is resolved...
    validations:
      required: true

  - type: dropdown
    id: risk-level
    attributes:
      label: Risk Assessment
      description: What's the risk level of this fix?
      options:
        - Low - Isolated fix with minimal impact
        - Medium - Some impact on related features
        - High - Significant changes or wide impact
    validations:
      required: true

  - type: checkboxes
    id: breaking-changes
    attributes:
      label: Breaking Changes
      description: Does this fix introduce any breaking changes?
      options:
        - label: No breaking changes
        - label: Breaking changes (documented in description)

  - type: checkboxes
    id: final-checklist
    attributes:
      label: Final Checklist
      options:
        - label: Root cause identified and documented
          required: true
        - label: Fix tested in multiple scenarios
          required: true
        - label: No new bugs introduced
          required: true
        - label: Code follows project standards
          required: true
        - label: Appropriate logging/error handling added
