name: 🚀 Feature
description: Submit a new feature or enhancement
title: "[FEATURE] "
labels: ["feature", "enhancement"]
assignees: []

body:
  - type: markdown
    attributes:
      value: |
        Thanks for contributing a new feature! Please provide detailed information about your enhancement.

  - type: input
    id: feature-summary
    attributes:
      label: Feature Summary
      description: Brief one-line summary of what this feature does
      placeholder: "Add user authentication with OAuth2"
    validations:
      required: true

  - type: textarea
    id: user-story
    attributes:
      label: User Story
      description: Describe the user story this feature addresses
      placeholder: "As a [user type], I want [goal] so that [benefit]"
    validations:
      required: true

  - type: textarea
    id: feature-description
    attributes:
      label: Detailed Description
      description: Provide a comprehensive description of the new feature
      placeholder: "Describe the feature in detail..."
    validations:
      required: true

  - type: input
    id: related-issues
    attributes:
      label: Related Issues
      description: Link related issues (e.g., "Implements \#123, Relates to \#456")
      placeholder: "Implements #, Relates to #"

  - type: dropdown
    id: feature-type
    attributes:
      label: Feature Type
      description: What type of feature is this?
      options:
        - User Interface Enhancement
        - API/Backend Feature
        - Performance Improvement
        - Developer Experience
        - Integration
        - Other
    validations:
      required: true

  - type: checkboxes
    id: api-changes
    attributes:
      label: API Changes
      description: Does this feature involve API changes?
      options:
        - label: No API changes
        - label: New APIs added
        - label: Existing APIs modified
        - label: Breaking changes introduced

  - type: textarea
    id: api-details
    attributes:
      label: API Changes Details
      description: If you have API changes, document them here
      placeholder: "List new endpoints, modified functions, breaking changes..."

  - type: textarea
    id: implementation-approach
    attributes:
      label: Technical Approach
      description: Describe your implementation approach and architectural decisions
      placeholder: "Explain the technical solution..."
    validations:
      required: true

  - type: checkboxes
    id: testing-completed
    attributes:
      label: Testing
      description: What testing has been completed?
      options:
        - label: Unit tests added for new functionality
          required: true
        - label: Integration tests updated
        - label: End-to-end tests added/updated
        - label: Manual testing completed
          required: true
        - label: Edge cases tested
        - label: Performance testing completed

  - type: textarea
    id: testing-steps
    attributes:
      label: Manual Testing Steps
      description: Provide step-by-step testing instructions
      placeholder: |
        1. Navigate to...
        2. Click on...
        3. Verify that...
    validations:
      required: true

  - type: checkboxes
    id: documentation
    attributes:
      label: Documentation
      description: Documentation updates completed
      options:
        - label: README updated
        - label: API documentation updated
        - label: User guide updated
        - label: Code comments added
        - label: CHANGELOG updated
          required: true

  - type: dropdown
    id: performance-impact
    attributes:
      label: Performance Impact
      description: What is the expected performance impact?
      options:
        - No performance impact expected
        - Performance improvement
        - Minimal performance impact
        - Significant performance impact (documented below)
    validations:
      required: true

  - type: textarea
    id: performance-notes
    attributes:
      label: Performance Notes
      description: If there are performance concerns, describe them
      placeholder: "Describe any performance implications..."

  - type: dropdown
    id: security-impact
    attributes:
      label: Security Impact
      description: Are there any security implications?
      options:
        - No security implications
        - Security improvements included
        - Security review completed
        - Security concerns noted below
    validations:
      required: true

  - type: textarea
    id: security-notes
    attributes:
      label: Security Notes
      description: If there are security concerns, describe them
      placeholder: "Describe any security implications..."

  - type: checkboxes
    id: final-checklist
    attributes:
      label: Final Checklist
      description: Complete this checklist before submitting
      options:
        - label: Code follows project style guidelines
          required: true
        - label: Self-review completed
          required: true
        - label: No new warnings or errors introduced
          required: true
        - label: Feature flag implemented (if applicable)
        - label: Dependencies justified and documented
