import { SolutionCatalogueTableEntry } from "./types";

export const DefaultSolutionTableConfig = {
	selectedItems: Array<SolutionCatalogueTableEntry>(),
	items: [
		{
			path: "name",
			key: "column.name",
			label: "column.name",
			selected: true,
			sortable: true,
			groupable: true,
		},
		{
			path: "platform/name",
			key: "column.platform",
			label: "column.platform",
			selected: true,
			sortable: true,
			groupable: true,
		},
		{
			path: "cleanCoreRating_code",
			key: "column.cleanCoreLevel",
			label: "column.cleanCoreLevel",
			selected: true,
			sortable: true,
			groupable: true,
		},
		{
			path: "codeQualityRating_code",
			key: "column.codeQualityLevel",
			label: "column.codeQualityLevel",
			selected: true,
			sortable: true,
			groupable: true,
		},
		{
			path: "solutionStatus_code",
			key: "column.status",
			label: "column.status",
			selected: true,
			sortable: true,
			groupable: true,
		},
		{
			path: "costCenter",
			key: "column.costCenter",
			label: "column.costCenter",
			selected: true,
			sortable: true,
			groupable: true,
		},
		{
			path: "businessCriticality/code",
			key: "column.businessCriticality",
			label: "column.businessCriticality",
			selected: true,
			sortable: true,
			groupable: true,
		},
		{
			path: "description",
			key: "column.description",
			label: "column.description",
			selected: false,
			sortable: true,
			groupable: true,
		},
		{
			path: "createdAt",
			key: "column.createdOn",
			label: "column.createdOn",
			selected: false,
			sortable: true,
			groupable: true,
		},
		{
			path: "createdBy",
			key: "column.createdBy",
			label: "column.createdBy",
			selected: false,
			sortable: true,
			groupable: true,
		},
		{
			path: "modifiedAt",
			key: "column.lastModified",
			label: "column.lastModified",
			selected: false,
			sortable: true,
			groupable: true,
		},
		{
			path: "modifiedBy",
			key: "column.lastModifiedBy",
			label: "column.lastModifiedBy",
			selected: false,
			sortable: true,
			groupable: true,
		},
		{
			path: "packageNamespace",
			key: "column.packageNamespace",
			label: "column.packageNamespace",
			selected: false,
			sortable: true,
			groupable: true,
		},
		{
			path: "repository",
			key: "column.repository",
			label: "column.repository",
			selected: false,
			sortable: true,
			groupable: true,
		},
		{
			path: "team/teamName",
			key: "column.team",
			label: "column.team",
			selected: false,
			sortable: true,
			groupable: true,
		},
		{
			path: "owner/fullName",
			key: "column.owner",
			label: "column.owner",
			selected: false,
			sortable: true,
			groupable: true,
		},
	],
};
